// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJKQ9eDYCIBqP4Pld6fOOPxc0KoDr2jqc',
    appId: '1:424113048334:web:741de6f77a3f64a849255f',
    messagingSenderId: '424113048334',
    projectId: 'transporte-inteligente-v2',
    authDomain: 'transporte-inteligente-v2.firebaseapp.com',
    databaseURL: 'https://transporte-inteligente-v2-default-rtdb.firebaseio.com',
    storageBucket: 'transporte-inteligente-v2.firebasestorage.app',
    measurementId: 'G-F3FRW2KWMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgSrcCRQ6zKdnqmwwRNQHjFMcw4ycA-PA',
    appId: '1:424113048334:android:4a8142ea92824ccf49255f',
    messagingSenderId: '424113048334',
    projectId: 'transporte-inteligente-v2',
    databaseURL: 'https://transporte-inteligente-v2-default-rtdb.firebaseio.com',
    storageBucket: 'transporte-inteligente-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoW2Z-QFokbX7ls1O60Q-ymQHGJmyqdjE',
    appId: '1:424113048334:ios:ece26c4bb647ed2749255f',
    messagingSenderId: '424113048334',
    projectId: 'transporte-inteligente-v2',
    databaseURL: 'https://transporte-inteligente-v2-default-rtdb.firebaseio.com',
    storageBucket: 'transporte-inteligente-v2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJKQ9eDYCIBqP4Pld6fOOPxc0KoDr2jqc',
    appId: '1:424113048334:web:5646f6c53957301149255f',
    messagingSenderId: '424113048334',
    projectId: 'transporte-inteligente-v2',
    authDomain: 'transporte-inteligente-v2.firebaseapp.com',
    databaseURL: 'https://transporte-inteligente-v2-default-rtdb.firebaseio.com',
    storageBucket: 'transporte-inteligente-v2.firebasestorage.app',
    measurementId: 'G-WKKB699F0G',
  );

}